### ISSUE TITLE
go mod is not work with structomap

### ISSUE THREAD

**Issue by cemkiy** [danhper/structomap#3]
I am trying to use go modules. But my packages are giving error after go build command.

my code

```go
import (
	"github.com/danhper/structomap"
)

// Serializer used in constructing maps to output JSON
type Serializer struct {
	*structomap.Base
}
```

output

```bash
./models.go:<line number>: imported and not used: "github.com/tuvistavie/structomap" as serializer
./models.go:<line number>: undefined: structomap
```

**Comment by danhper** [comment]
Hi.
I changed my username at some point, which might be what is causing the issue. 
All occurrences of `github.com/tuvistavie/structomap` should now be `github.com/danhper/structomap`.
Could you please check that this is the case?
Thanks.

**Comment by cemkiy** [comment]
I noticed that situation too. I have tried with danhper and error is not gone. I have tried with my fork(github.com/cemkiy/structomap) and error is not gone. I am working on it.

**Comment by cemkiy** [comment]
Okey, i tried many things then found the solution. 

```
$ go mod init
$ go build
$ go get github.com/danhper/structomap@0.6.1
```
Why we need the last command?

After go build command, structomap version is v0.1.0. But your last version is 0.6.1. Therefore go mod is giving errors.

I tried get your last release and done.

And the question is why go mod getting old version?
My answer is probably "v" letter. Your first release is v0.1.0, but other releases are only starting with 0, not including v letter. This is maybe fixed all problems.

**Comment by danhper** [comment]
Interesting. Thanks for looking into this.
I just pushed a tag `v0.6.2` to see if it makes any difference.
Could you let me know how that goes please?
Thanks a lot!

**Comment by cemkiy** [comment]
it's worked.

go.mod output is:

```bash
github.com/danhper/structomap v0.6.2
```

go.sum output is:

```bash
github.com/danhper/structomap v0.6.2 h1:VryUhPR3Ju+FeXHXTL2RGPbRmIX/mN768jULh9weylM=
github.com/danhper/structomap v0.6.2/go.mod h1:qmif0PLXZftsShsS0miHLhWv4VRR8awMUPnYxHAJCjg=
```

I found this website on my researches. [https://research.swtch.com/vgo-module#from_repository_to_modules](https://research.swtch.com/vgo-module#from_repository_to_modules)

it says 

> The leading v is required, and having three numbers is also required. 

thanks for your interest.we can close issue.
